### ISSUE TITLE
error about obj_models/val/02876657/d3b53f56b4a7b3b3c9f016d57db96408/model.obj when run shape_data.py and pose_data.py

### ISSUE THREAD

**Issue by EasonEdison** [mentian/object-deformnet#24]
Dear author, thank you for releasing such a wonderful work!
I met a problem when running shape_data.py to preprocess the object models.
The info is as follows.

Traceback (most recent call last): File "/home/user/object-deformnet/preprocess/shape_data.py", line 217, in <module> save_nocs_model_to_file(obj_model_dir) File "/home/user/object-deformnet/preprocess/shape_data.py", line 33, in save_nocs_model_to_file model_points = sample_points_from_mesh(path_to_mesh_model, 1024, fps=True, ratio=3) File "../lib/utils.py", line 147, in sample_points_from_mesh points = uniform_sample(vertices, faces, ratio*n_pts, with_normal) File "../lib/utils.py", line 100, in uniform_sample faces = vertices[faces] IndexError: arrays used as indices must be of integer (or boolean) type

![image](https://user-images.githubusercontent.com/31425634/141981722-d3eedcac-6143-4b5d-b059-d7f672f5fec2.png)

now I select to skip this case in shape_data.py, but it still show in pose_data.py, as follow, how should I do? should I still skip it ?
![image](https://user-images.githubusercontent.com/31425634/141982024-304ace50-0f16-4a47-b2e0-ef35d7f28241.png)

**Comment by EasonEdison** [comment]
I skip this instance, then run train_ae.py and train_deform.py and evaluate.py, it doesn't seem to have any effect compared to the author's model, but I still want to get reply from author.

**Comment by nicu233** [comment]
> I skip this instance, then run train_ae.py and train_deform.py and evaluate.py, it doesn't seem to have any effect compared to the author's model, but I still want to get reply from author.

I get same error. When i try to open this model.obj file, some wrong with it.
it is only 1kb, seem differently with other model.obj.
did you get rid of this problem. what should i to do to solve this problem. skip it?

**Comment by nicu233** [comment]
> I skip this instance, then run train_ae.py and train_deform.py and evaluate.py, it doesn't seem to have any effect compared to the author's model, but I still want to get reply from author.

There another question about pose_data.py. When I run function annotate_test_data, it can not find folder **results/noce_results**.  **Is results/noce_results just data/gts**? I find they hava same child folder, but data/gts 's pkl files do not have gt_handle_visibility.  It seem like only for mug, I just comment all lines about handle_visibility and gt_handle_visibility. I dont know would this comment effect evaluate and train.
Can you share what modifiy about pose_data.py file you have. 
Waiting your reply.

**Comment by rohanksaxena** [comment]
Has anyone been able to get past this issue?

**Comment by Van5SE** [comment]
Hi guys, can anybody solve the problem by other methods than just skipping it?

**Comment by yl-wang996** [comment]
same problem by me, does someone have a solution for this?

**Comment by yl-wang996** [comment]
I found the problem, the file: `obj_models/val/02876657/d3b53f56b4a7b3b3c9f016d57db96408/model.obj` has the wrong content, this is the problem with the NOCS dataset.

**Comment by yl-wang996** [comment]
problem was resolved by [here](https://github.com/mentian/object-deformnet/issues/3#issuecomment-698858332), you can simply download the files and put it in the right place.
